using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using FlexLabs.EntityFrameworkCore.Upsert;
using WindLordApi.Data.Models;
using WindLordApi.Data.Repositories;

namespace WindLordApi.Data.Services;

public class LatestStationDataService : ILatestStationDataService
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly ILogger<LatestStationDataService> _logger;
    private const int BatchSize = 1000; // Process in batches to avoid parameter limits

    public LatestStationDataService(IUnitOfWork unitOfWork, ILogger<LatestStationDataService> logger)
    {
        _unitOfWork = unitOfWork;
        _logger = logger;
    }

    public async Task<int> UpsertManyAsync(LatestStationData[] latestStationDataArray, CancellationToken cancellationToken = default)
    {
        if (latestStationDataArray == null || latestStationDataArray.Length == 0)
        {
            throw new ArgumentException("Latest station data array cannot be null or empty", nameof(latestStationDataArray));
        }
        var records = latestStationDataArray.Where(lsd => lsd is not null).ToList();
        if (records.Count == 0)
        {
            throw new ArgumentException("Latest station data array cannot contain only null elements", nameof(latestStationDataArray));
        }

        var totalUpserted = 0;

        // Process in batches to avoid parameter limits
        for (int i = 0; i < records.Count; i += BatchSize)
        {
            var batch = records.Skip(i).Take(BatchSize).ToList();
            totalUpserted += await UpsertBatchAsync(batch, cancellationToken);
        }

        return totalUpserted;
    }

    private async Task<int> UpsertBatchAsync(List<LatestStationData> batch, CancellationToken cancellationToken)
    {
        if (batch.Count == 0) return 0;

        // Use explicit transaction for Supabase connection pooler compatibility
        await using var transaction = await _unitOfWork.BeginTransactionAsync(cancellationToken);
        try
        {
            // Use FlexLabs upsert: ON CONFLICT (station_id) DO UPDATE
            // This is type-safe and eliminates SQL injection risks
            var upsertedCount = await _unitOfWork.Context.UpsertRange<LatestStationData>(batch)
                .On(lsd => lsd.StationId)
                .WhenMatched((existing, incoming) => new LatestStationData
                {
                    // Id is not set - primary key is preserved automatically
                    StationId = incoming.StationId,
                    WindSpeed = incoming.WindSpeed,
                    WindGust = incoming.WindGust,
                    Direction = incoming.Direction,
                    Temperature = incoming.Temperature,
                    UpdatedAt = incoming.UpdatedAt,
                    WindMinSpeed = incoming.WindMinSpeed
                })
                .RunAsync(cancellationToken);

            await _unitOfWork.CommitTransactionAsync(transaction, cancellationToken);

            return upsertedCount;
        }
        catch (Exception ex)
        {
            await _unitOfWork.RollbackTransactionAsync(transaction, cancellationToken);
            _logger.LogError(ex, "Failed to upsert latest station data batch of {Count} records", batch.Count);
            throw;
        }
    }

    /// <summary>
    /// Converts StationData array to LatestStationData array.
    /// Maps all matching fields and excludes IsCompressed (not in LatestStationData).
    /// Id field is left as default - database will generate on insert.
    /// </summary>
    public static LatestStationData[] ConvertFromStationData(StationData[] stationDataArray)
    {
        if (stationDataArray == null || stationDataArray.Length == 0)
        {
            return Array.Empty<LatestStationData>();
        }

        return stationDataArray
            .Where(sd => sd is not null)
            .Select(sd => new LatestStationData
            {
                // Id is not set - will be generated by database on insert
                StationId = sd.StationId,
                WindSpeed = sd.WindSpeed,
                WindGust = sd.WindGust,
                Direction = sd.Direction,
                Temperature = sd.Temperature,
                UpdatedAt = sd.UpdatedAt,
                WindMinSpeed = sd.WindMinSpeed
            })
            .ToArray();
    }
}

