using WindLordApi.Data.Models;

namespace WindLordApi.Integrations.WindsMobi;

/// <summary>
/// Maps WindsMobi API response data to domain models for database storage.
/// </summary>
public class WindsMobiMappingService : IWindsMobiMapping
{
    /// <summary>
    /// Conversion factor from km/h to m/s. WindsMobi API returns wind values in km/h.
    /// </summary>
    private const decimal KmhToMs = 3.6m;

    /// <summary>
    /// Maps WindsMobi station data to StationData format for database storage.
    /// Filters out stations without valid observation data or coordinates.
    /// </summary>
    public List<StationData> MapToStationData(IReadOnlyList<WindsMobiStation> stations)
    {
        return stations
            .Where(IsValidStation)
            .Where(s => s.Last?.Id != null && s.Last.WindAverage.HasValue)
            .Select(station =>
            {
                var direction = station.Last!.WindDirection ?? 0;
                direction = ((direction % 360) + 360) % 360;

                return new StationData
                {
                    // Id is not set - will be generated by database
                    StationId = station.Id,
                    WindSpeed = Math.Round(station.Last.WindAverage!.Value / KmhToMs, 1),
                    WindGust = station.Last.WindMax.HasValue
                        ? Math.Round(station.Last.WindMax.Value / KmhToMs, 1)
                        : null,
                    WindMinSpeed = null, // Not provided by WindsMobi API
                    Direction = direction,
                    Temperature = station.Last.Temperature,
                    UpdatedAt = DateTimeOffset.FromUnixTimeSeconds(station.Last.Id!.Value).UtcDateTime,
                    IsCompressed = false
                };
            })
            .ToList();
    }

    /// <summary>
    /// Maps WindsMobi station data to WeatherStation format for database storage.
    /// Filters out stations without valid coordinates.
    /// </summary>
    public List<WeatherStation> MapToWeatherStation(IReadOnlyList<WindsMobiStation> stations)
    {
        return stations
            .Where(IsValidStation)
            .Select(station =>
            {
                // GeoJSON coordinates: [longitude, latitude]
                var longitude = Math.Round((double)station.Location!.Coordinates![0], 5);
                var latitude = Math.Round((double)station.Location.Coordinates[1], 5);

                return new WeatherStation
                {
                    // Id is not set - will be generated by database
                    StationId = station.Id,
                    Name = station.ShortName ?? station.Id,
                    Latitude = (decimal)latitude,
                    Longitude = (decimal)longitude,
                    Altitude = station.Altitude,
                    Country = null,
                    IsActive = true,
                    Provider = station.ProviderCode,
                    IsMain = false
                    // UpdatedAt is not set - will be set by database
                };
            })
            .ToList();
    }

    /// <summary>
    /// Validates that a station has valid coordinates (non-null, non-zero, within valid range).
    /// </summary>
    private static bool IsValidStation(WindsMobiStation station)
    {
        if (string.IsNullOrWhiteSpace(station.Id))
            return false;

        if (station.Location?.Coordinates == null || station.Location.Coordinates.Length < 2)
            return false;

        var lng = (double)station.Location.Coordinates[0];
        var lat = (double)station.Location.Coordinates[1];

        return lat != 0
            && lng != 0
            && lat >= -90
            && lat <= 90
            && lng >= -180
            && lng <= 180;
    }
}
