// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WindLordApi.Data;

#nullable disable

namespace WindLordApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251221125519_ForeCastCacheAndParaglidingLocation")]
    partial class ForeCastCacheAndParaglidingLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WindLordApi.Data.Models.ForecastCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BoundaryLayerHeight")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("boundary_layer_height");

                    b.Property<decimal?>("Cape")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("cape");

                    b.Property<int?>("CloudCover")
                        .HasColumnType("integer")
                        .HasColumnName("cloud_cover");

                    b.Property<int?>("CloudCoverHigh")
                        .HasColumnType("integer")
                        .HasColumnName("cloud_cover_high");

                    b.Property<int?>("CloudCoverLow")
                        .HasColumnType("integer")
                        .HasColumnName("cloud_cover_low");

                    b.Property<int?>("CloudCoverMid")
                        .HasColumnType("integer")
                        .HasColumnName("cloud_cover_mid");

                    b.Property<decimal?>("ConvectiveInhibition")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("convective_inhibition");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("FreezingLevelHeight")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("freezing_level_height");

                    b.Property<decimal?>("GeopotentialHeight1000hpa")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("geopotential_height_1000hpa");

                    b.Property<decimal?>("GeopotentialHeight700hpa")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("geopotential_height_700hpa");

                    b.Property<decimal?>("GeopotentialHeight850hpa")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("geopotential_height_850hpa");

                    b.Property<decimal?>("GeopotentialHeight925hpa")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("geopotential_height_925hpa");

                    b.Property<short?>("IsDay")
                        .HasColumnType("smallint")
                        .HasColumnName("is_day");

                    b.Property<bool>("IsYrData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_yr_data");

                    b.Property<decimal?>("LandingGust")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("landing_gust");

                    b.Property<decimal?>("LandingWind")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("landing_wind");

                    b.Property<int?>("LandingWindDirection")
                        .HasColumnType("integer")
                        .HasColumnName("landing_wind_direction");

                    b.Property<decimal?>("LiftedIndex")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("lifted_index");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<decimal?>("Precipitation")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("precipitation");

                    b.Property<double?>("PrecipitationMax")
                        .HasColumnType("double precision")
                        .HasColumnName("precipitation_max");

                    b.Property<double?>("PrecipitationMin")
                        .HasColumnType("double precision")
                        .HasColumnName("precipitation_min");

                    b.Property<float?>("PrecipitationProbability")
                        .HasColumnType("real")
                        .HasColumnName("precipitation_probability");

                    b.Property<decimal?>("PressureMsl")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("pressure_msl");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temperature");

                    b.Property<decimal?>("Temperature1000hpa")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temperature_1000hpa");

                    b.Property<decimal?>("Temperature700hpa")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temperature_700hpa");

                    b.Property<decimal?>("Temperature850hpa")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temperature_850hpa");

                    b.Property<decimal?>("Temperature925hpa")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temperature_925hpa");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WeatherCode")
                        .HasColumnType("text")
                        .HasColumnName("weather_code");

                    b.Property<int?>("WindDirection")
                        .HasColumnType("integer")
                        .HasColumnName("wind_direction");

                    b.Property<int?>("WindDirection1000hpa")
                        .HasColumnType("integer")
                        .HasColumnName("wind_direction_1000hpa");

                    b.Property<int?>("WindDirection700hpa")
                        .HasColumnType("integer")
                        .HasColumnName("wind_direction_700hpa");

                    b.Property<int?>("WindDirection850hpa")
                        .HasColumnType("integer")
                        .HasColumnName("wind_direction_850hpa");

                    b.Property<int?>("WindDirection925hpa")
                        .HasColumnType("integer")
                        .HasColumnName("wind_direction_925hpa");

                    b.Property<decimal?>("WindGusts")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("wind_gusts");

                    b.Property<decimal?>("WindSpeed")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("wind_speed");

                    b.Property<decimal?>("WindSpeed1000hpa")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("wind_speed_1000hpa");

                    b.Property<decimal?>("WindSpeed700hpa")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("wind_speed_700hpa");

                    b.Property<decimal?>("WindSpeed850hpa")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("wind_speed_850hpa");

                    b.Property<decimal?>("WindSpeed925hpa")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("wind_speed_925hpa");

                    b.HasKey("Id");

                    b.HasAlternateKey("LocationId", "Time")
                        .HasName("forecast_cache_location_id_time_key");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("forecast_cache_location_id_idx");

                    b.HasIndex("Time")
                        .HasDatabaseName("idx_forecast_cache_time");

                    b.HasIndex("LocationId", "Time")
                        .HasDatabaseName("idx_forecast_cache_location_time");

                    b.ToTable("forecast_cache", t =>
                        {
                            t.HasCheckConstraint("forecast_cache_is_day_check", "is_day = ANY (ARRAY[0, 1])");
                        });
                });

            modelBuilder.Entity("WindLordApi.Data.Models.LatestStationData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("station_id");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("WindGust")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("wind_gust");

                    b.Property<decimal?>("WindMinSpeed")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("wind_min_speed");

                    b.Property<decimal>("WindSpeed")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("wind_speed");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .IsUnique()
                        .HasDatabaseName("latest_station_data_station_id_key");

                    b.ToTable("latest_station_data", t =>
                        {
                            t.HasCheckConstraint("latest_station_data_direction_check", "direction >= 0 AND direction <= 360");
                        });
                });

            modelBuilder.Entity("WindLordApi.Data.Models.ParaglidingLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Altitude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("altitude");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Norway")
                        .HasColumnName("country");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("E")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("e");

                    b.Property<string>("FlightlogId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("flightlog_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_main");

                    b.Property<int?>("LandingAltitude")
                        .HasColumnType("integer")
                        .HasColumnName("landing_altitude");

                    b.Property<float?>("LandingLatitude")
                        .HasColumnType("real")
                        .HasColumnName("landing_latitude");

                    b.Property<float?>("LandingLongitude")
                        .HasColumnType("real")
                        .HasColumnName("landing_longitude");

                    b.Property<float>("Latitude")
                        .HasColumnType("real")
                        .HasColumnName("latitude");

                    b.Property<float>("Longitude")
                        .HasColumnType("real")
                        .HasColumnName("longitude");

                    b.Property<bool>("N")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("n");

                    b.Property<bool>("NE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ne");

                    b.Property<bool>("NW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("nw");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<bool>("S")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("s");

                    b.Property<bool>("SE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("se");

                    b.Property<bool>("SW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sw");

                    b.Property<string>("Timezone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("timezone");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("W")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("w");

                    b.HasKey("Id");

                    b.HasIndex("FlightlogId")
                        .IsUnique()
                        .HasDatabaseName("all_paragliding_locations_flightlog_id_key");

                    b.HasIndex("IsMain")
                        .HasDatabaseName("all_paragliding_locations_is_main_idx");

                    b.HasIndex("Name")
                        .HasDatabaseName("all_paragliding_locations_name_idx");

                    b.HasIndex("Country", "IsActive")
                        .HasDatabaseName("all_paragliding_locations_country_is_active_idx")
                        .HasFilter("is_active = true");

                    b.HasIndex("IsActive", "Latitude", "Longitude")
                        .HasDatabaseName("all_paragliding_locations_is_active_latitude_longitude_idx")
                        .HasFilter("is_active = true");

                    b.ToTable("all_paragliding_locations");
                });

            modelBuilder.Entity("WindLordApi.Data.Models.StationData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<bool>("IsCompressed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_compressed");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("station_id");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("WindGust")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("wind_gust");

                    b.Property<decimal?>("WindMinSpeed")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("wind_min_speed");

                    b.Property<decimal>("WindSpeed")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("wind_speed");

                    b.HasKey("Id");

                    b.HasAlternateKey("StationId", "UpdatedAt");

                    b.HasIndex("StationId", "UpdatedAt")
                        .IsUnique()
                        .HasDatabaseName("unique_station_timestamp");

                    b.ToTable("station_data", t =>
                        {
                            t.HasCheckConstraint("station_data_direction_check", "direction >= 0 AND direction <= 360");
                        });
                });

            modelBuilder.Entity("WindLordApi.Data.Models.WeatherStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("Altitude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("altitude");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_main");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("station_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .IsUnique()
                        .HasDatabaseName("weather_stations_station_id_unique");

                    b.ToTable("weather_stations", t =>
                        {
                            t.HasCheckConstraint("check_provider_not_empty", "provider IS NOT NULL AND provider <> ''");
                        });
                });

            modelBuilder.Entity("WindLordApi.Data.Models.ForecastCache", b =>
                {
                    b.HasOne("WindLordApi.Data.Models.ParaglidingLocation", "ParaglidingLocation")
                        .WithMany("ForecastCaches")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("forecast_cache_location_id_fkey");

                    b.Navigation("ParaglidingLocation");
                });

            modelBuilder.Entity("WindLordApi.Data.Models.StationData", b =>
                {
                    b.HasOne("WindLordApi.Data.Models.WeatherStation", "WeatherStation")
                        .WithMany("StationData")
                        .HasForeignKey("StationId")
                        .HasPrincipalKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_station_data_station_id");

                    b.Navigation("WeatherStation");
                });

            modelBuilder.Entity("WindLordApi.Data.Models.ParaglidingLocation", b =>
                {
                    b.Navigation("ForecastCaches");
                });

            modelBuilder.Entity("WindLordApi.Data.Models.WeatherStation", b =>
                {
                    b.Navigation("StationData");
                });
#pragma warning restore 612, 618
        }
    }
}
