using WindLordApi.Data.Models;

namespace WindLordApi.Integrations.MetFrost;

/// <summary>
/// Maps MET observations data to domain models for database storage.
/// Groups observations by station and time, extracting the latest values for each parameter.
/// </summary>
public class MetFrostMappingService : IMetFrostMapping
{
    /// <summary>
    /// Maps MET observations data to StationData format for database storage.
    /// Groups observations by station and time, extracting the latest values for each parameter.
    /// </summary>
    /// <param name="observationsData">Array of MET observations data points</param>
    /// <returns>Array of StationData objects (without Id) ready for database insertion</returns>
    public List<StationData> MapMetObservationsToStationData(
        IReadOnlyList<MetObservationsData> observationsData)
    {
        var stationDataMap = new Dictionary<string, StationDataBuilder>();

        // Process each data point
        foreach (var dataPoint in observationsData)
        {
            // Extract station ID (remove sensor number suffix like :0)
            var stationId = dataPoint.SourceId.Split(':')[0];
            var referenceTime = dataPoint.ReferenceTime;

            // Get or create station data entry
            // Use UtcDateTime to ensure UTC Kind (required by PostgreSQL timestamp with time zone)
            var utcDateTime = referenceTime.UtcDateTime;
            if (!stationDataMap.TryGetValue(stationId, out var stationData))
            {
                stationData = new StationDataBuilder
                {
                    StationId = stationId,
                    UpdatedAt = utcDateTime
                };
                stationDataMap[stationId] = stationData;
            }

            // Update timestamp to the latest one
            if (utcDateTime > stationData.UpdatedAt)
            {
                stationData.UpdatedAt = utcDateTime;
            }

            // Process each observation in the data point
            foreach (var observation in dataPoint.Observations)
            {
                var elementId = observation.ElementId;
                var value = observation.Value;

                switch (elementId)
                {
                    case "wind_speed":
                        stationData.WindSpeed = (decimal)value;
                        break;

                    case "max(wind_speed_of_gust PT10M)":
                        // Prefer 10-minute resolution gust data (more granular)
                        stationData.WindGust = (decimal)value;
                        break;

                    case "max(wind_speed_of_gust PT1H)":
                        // Use hourly resolution gust data as fallback (if PT10M not available)
                        if (stationData.WindGust == null)
                        {
                            stationData.WindGust = (decimal)value;
                        }
                        break;

                    case "wind_from_direction":
                        stationData.Direction = (int)Math.Round(value);
                        break;

                    case "air_temperature":
                        stationData.Temperature = (decimal)value;
                        break;

                    default:
                        // Skip unknown elements
                        break;
                }
            }
        }

        // Convert map to list and filter out incomplete records
        var stationDataList = stationDataMap.Values
            .Where(data =>
                // Only include records that have at least wind_speed and direction
                data.WindSpeed.HasValue && data.Direction.HasValue)
            .Select(data =>
            {
                // Normalize wind direction to ensure it's within 0-360 range
                var direction = data.Direction!.Value;
                direction = ((direction % 360) + 360) % 360;

                return new StationData
                {
                    // Id is not set - will be generated by database
                    StationId = data.StationId,
                    WindSpeed = data.WindSpeed!.Value,
                    WindGust = data.WindGust,
                    WindMinSpeed = null,
                    Direction = direction,
                    Temperature = data.Temperature,
                    UpdatedAt = data.UpdatedAt,
                    IsCompressed = false
                };
            })
            .ToList();

        return stationDataList;
    }

    /// <summary>
    /// Maps Met Frost API response data to WeatherStation format for database storage.
    /// </summary>
    /// <param name="metFrostData">Array of MET Frost station data</param>
    /// <returns>Array of WeatherStation objects (without Id and UpdatedAt) ready for database insertion</returns>
    public List<WeatherStation> MapMetFrostToWeatherStation(
        IReadOnlyList<MetFrostStation> metFrostData)
    {
        return metFrostData
            .Where(station =>
            {
                // Filter out stations with invalid or missing coordinates
                if (station.Geometry == null || station.Geometry.Coordinates == null || station.Geometry.Coordinates.Length != 2)
                {
                    return false;
                }

                var longitude = station.Geometry.Coordinates[0];
                var latitude = station.Geometry.Coordinates[1];

                return longitude != 0
                    && latitude != 0
                    && latitude >= -90
                    && latitude <= 90
                    && longitude >= -180
                    && longitude <= 180;
            })
            .Select(station =>
            {
                var longitude = station.Geometry!.Coordinates[0];
                var latitude = station.Geometry.Coordinates[1];

                return new WeatherStation
                {
                    // Id is not set - will be generated by database
                    StationId = station.Id,
                    Name = station.Name ?? station.Id, // Use station ID as fallback if name is null
                    Latitude = (decimal)Math.Round(latitude, 4),
                    Longitude = (decimal)Math.Round(longitude, 4),
                    Altitude = station.Masl != null ? (int)Math.Round(station.Masl.Value) : 0,
                    Country = station.Country ?? "UKJENT",
                    IsActive = true,
                    Provider = "MET",
                    IsMain = station.Country == "Norge"
                    // UpdatedAt is not set - will be set by database
                };
            })
            .ToList();
    }

    /// <summary>
    /// Helper class to build StationData incrementally.
    /// </summary>
    private class StationDataBuilder
    {
        public string StationId { get; set; } = string.Empty;
        public decimal? WindSpeed { get; set; }
        public decimal? WindGust { get; set; }
        public int? Direction { get; set; }
        public decimal? Temperature { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

