using WindLordApi.Data.Models;

namespace WindLordApi.Integrations.MetFrost;

/// <summary>
/// Maps MET observations data to StationData format for database storage.
/// Groups observations by station and time, extracting the latest values for each parameter.
/// </summary>
public static class MetFrostMapping
{
    /// <summary>
    /// Maps MET observations data to StationData format for database storage.
    /// Groups observations by station and time, extracting the latest values for each parameter.
    /// </summary>
    /// <param name="observationsData">Array of MET observations data points</param>
    /// <returns>Array of StationData objects (without Id) ready for database insertion</returns>
    public static List<StationData> MapMetObservationsToStationData(
        IReadOnlyList<MetObservationsData> observationsData)
    {
        var stationDataMap = new Dictionary<string, StationDataBuilder>();

        // Process each data point
        foreach (var dataPoint in observationsData)
        {
            // Extract station ID (remove sensor number suffix like :0)
            var stationId = dataPoint.SourceId.Split(':')[0];
            var referenceTime = dataPoint.ReferenceTime;

            // Get or create station data entry
            if (!stationDataMap.TryGetValue(stationId, out var stationData))
            {
                stationData = new StationDataBuilder
                {
                    StationId = stationId,
                    UpdatedAt = referenceTime.DateTime
                };
                stationDataMap[stationId] = stationData;
            }

            // Update timestamp to the latest one
            if (referenceTime.DateTime > stationData.UpdatedAt)
            {
                stationData.UpdatedAt = referenceTime.DateTime;
            }

            // Process each observation in the data point
            foreach (var observation in dataPoint.Observations)
            {
                var elementId = observation.ElementId;
                var value = observation.Value;

                switch (elementId)
                {
                    case "wind_speed":
                        stationData.WindSpeed = (decimal)value;
                        break;

                    case "max(wind_speed_of_gust PT10M)":
                        // Prefer 10-minute resolution gust data (more granular)
                        stationData.WindGust = (decimal)value;
                        break;

                    case "max(wind_speed_of_gust PT1H)":
                        // Use hourly resolution gust data as fallback (if PT10M not available)
                        if (stationData.WindGust == null)
                        {
                            stationData.WindGust = (decimal)value;
                        }
                        break;

                    case "wind_from_direction":
                        stationData.Direction = (int)Math.Round(value);
                        break;

                    case "air_temperature":
                        stationData.Temperature = (decimal)value;
                        break;

                    default:
                        // Skip unknown elements
                        break;
                }
            }
        }

        // Convert map to list and filter out incomplete records
        var stationDataList = stationDataMap.Values
            .Where(data => 
                // Only include records that have at least wind_speed and direction
                data.WindSpeed.HasValue && data.Direction.HasValue)
            .Select(data => new StationData
            {
                // Id is not set - will be generated by database
                StationId = data.StationId,
                WindSpeed = data.WindSpeed!.Value,
                WindGust = data.WindGust,
                WindMinSpeed = null,
                Direction = data.Direction!.Value,
                Temperature = data.Temperature,
                UpdatedAt = data.UpdatedAt,
                IsCompressed = false
            })
            .ToList();

        return stationDataList;
    }

    /// <summary>
    /// Helper class to build StationData incrementally.
    /// </summary>
    private class StationDataBuilder
    {
        public string StationId { get; set; } = string.Empty;
        public decimal? WindSpeed { get; set; }
        public decimal? WindGust { get; set; }
        public int? Direction { get; set; }
        public decimal? Temperature { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

