using Microsoft.EntityFrameworkCore;
using WindLordApi.Data.Models;

namespace WindLordApi.Data;

public class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public DbSet<WeatherStation> WeatherStations { get; set; }
    public DbSet<StationData> StationData { get; set; }
    public DbSet<LatestStationData> LatestStationData { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Configure WeatherStation
        modelBuilder.Entity<WeatherStation>(entity =>
        {
            entity.HasKey(e => e.Id);

            // Database generates primary key IDs
            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .ValueGeneratedOnAdd();

            entity.HasIndex(e => e.StationId)
                .IsUnique()
                .HasDatabaseName("weather_stations_station_id_unique");

            // Check constraint: provider cannot be empty if not null
            entity.ToTable(t => t.HasCheckConstraint("check_provider_not_empty",
                "provider IS NOT NULL AND provider <> ''"));

            // Default values
            entity.Property(e => e.Altitude)
                .HasDefaultValue(0);

            entity.Property(e => e.IsActive)
                .HasDefaultValue(true);

            entity.Property(e => e.IsMain)
                .HasDefaultValue(false);

            // Convert DateTime to Unspecified kind when writing to 'timestamp without time zone'
            // This allows UTC DateTime values to be used in code while PostgreSQL stores them correctly
            entity.Property(e => e.UpdatedAt)
                .HasConversion(
                    v => v.HasValue ? DateTime.SpecifyKind(v.Value, DateTimeKind.Unspecified) : v,
                    v => v);

            entity.HasMany(e => e.StationData)
                .WithOne(e => e.WeatherStation)
                .HasPrincipalKey(e => e.StationId)
                .HasForeignKey(e => e.StationId)
                .HasConstraintName("fk_station_data_station_id")
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Configure StationData
        modelBuilder.Entity<StationData>(entity =>
        {
            entity.HasKey(e => e.Id);

            // Database generates primary key IDs
            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .ValueGeneratedOnAdd();

            // Configure alternate key for FlexLabs upsert matching
            // This tells EF Core (and FlexLabs) that (StationId, UpdatedAt) is a valid unique key
            entity.HasAlternateKey(e => new { e.StationId, e.UpdatedAt });

            entity.HasIndex(e => new { e.StationId, e.UpdatedAt })
                .IsUnique()
                .HasDatabaseName("unique_station_timestamp");

            // Check constraint: direction must be between 0 and 360
            entity.ToTable(t => t.HasCheckConstraint("station_data_direction_check",
                "direction >= 0 AND direction <= 360"));

            // Explicitly mark StationId and UpdatedAt as not value-generated for FlexLabs
            // Even though UpdatedAt has a default value, it's not autogenerated in the identity sense
            entity.Property(e => e.StationId)
                .ValueGeneratedNever();

            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .ValueGeneratedNever(); // Explicitly mark as not autogenerated for FlexLabs

            entity.Property(e => e.IsCompressed)
                .HasDefaultValue(false);
        });

        // Configure LatestStationData
        modelBuilder.Entity<LatestStationData>(entity =>
        {
            entity.HasKey(e => e.Id);

            // Database generates primary key IDs
            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .ValueGeneratedOnAdd();

            // Unique index on StationId (matching SQL constraint latest_station_data_station_id_key)
            entity.HasIndex(e => e.StationId)
                .IsUnique()
                .HasDatabaseName("latest_station_data_station_id_key");

            // Check constraint: direction must be between 0 and 360
            entity.ToTable(t => t.HasCheckConstraint("latest_station_data_direction_check",
                "direction >= 0 AND direction <= 360"));

            // Explicitly mark StationId and UpdatedAt as not value-generated for FlexLabs
            entity.Property(e => e.StationId)
                .ValueGeneratedNever();

            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .ValueGeneratedNever(); // Explicitly mark as not autogenerated for FlexLabs
        });
    }
}
