using Microsoft.EntityFrameworkCore;
using WindLordApi.Data.Models;

namespace WindLordApi.Data;

public class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public DbSet<WeatherStation> WeatherStations { get; set; }
    public DbSet<StationData> StationData { get; set; }
    public DbSet<LatestStationData> LatestStationData { get; set; }
    public DbSet<ParaglidingLocation> ParaglidingLocations { get; set; }
    public DbSet<ForecastCache> ForecastCaches { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Configure WeatherStation
        modelBuilder.Entity<WeatherStation>(entity =>
        {
            entity.HasKey(e => e.Id);

            // Database generates primary key IDs
            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .ValueGeneratedOnAdd();

            entity.HasIndex(e => e.StationId)
                .IsUnique()
                .HasDatabaseName("weather_stations_station_id_unique");

            // Check constraint: provider cannot be empty if not null
            entity.ToTable(t => t.HasCheckConstraint("check_provider_not_empty",
                "provider IS NOT NULL AND provider <> ''"));

            // Default values
            entity.Property(e => e.Altitude)
                .HasDefaultValue(0);

            entity.Property(e => e.IsActive)
                .HasDefaultValue(true);

            entity.Property(e => e.IsMain)
                .HasDefaultValue(false);

            entity.HasMany(e => e.StationData)
                .WithOne(e => e.WeatherStation)
                .HasPrincipalKey(e => e.StationId)
                .HasForeignKey(e => e.StationId)
                .HasConstraintName("fk_station_data_station_id")
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Configure StationData
        modelBuilder.Entity<StationData>(entity =>
        {
            entity.HasKey(e => e.Id);

            // Database generates primary key IDs
            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .ValueGeneratedOnAdd();

            // Configure alternate key for FlexLabs upsert matching
            // This tells EF Core (and FlexLabs) that (StationId, UpdatedAt) is a valid unique key
            entity.HasAlternateKey(e => new { e.StationId, e.UpdatedAt });

            entity.HasIndex(e => new { e.StationId, e.UpdatedAt })
                .IsUnique()
                .HasDatabaseName("unique_station_timestamp");

            // Check constraint: direction must be between 0 and 360
            entity.ToTable(t => t.HasCheckConstraint("station_data_direction_check",
                "direction >= 0 AND direction <= 360"));

            // Explicitly mark StationId and UpdatedAt as not value-generated for FlexLabs
            // Even though UpdatedAt has a default value, it's not autogenerated in the identity sense
            entity.Property(e => e.StationId)
                .ValueGeneratedNever();

            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .ValueGeneratedNever(); // Explicitly mark as not autogenerated for FlexLabs

            entity.Property(e => e.IsCompressed)
                .HasDefaultValue(false);
        });

        // Configure LatestStationData
        modelBuilder.Entity<LatestStationData>(entity =>
        {
            entity.HasKey(e => e.Id);

            // Database generates primary key IDs
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd();

            // Unique index on StationId (matching SQL constraint latest_station_data_station_id_key)
            entity.HasIndex(e => e.StationId)
                .IsUnique()
                .HasDatabaseName("latest_station_data_station_id_key");
        });

        // Configure ParaglidingLocation
        modelBuilder.Entity<ParaglidingLocation>(entity =>
        {
            entity.HasKey(e => e.Id);

            // Database generates primary key IDs
            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .ValueGeneratedOnAdd();

            // Composite index on IsActive, Latitude, Longitude (filtered)
            entity.HasIndex(e => new { e.IsActive, e.Latitude, e.Longitude })
                .HasDatabaseName("all_paragliding_locations_is_active_latitude_longitude_idx")
                .HasFilter("is_active = true");

            // Index on IsMain
            entity.HasIndex(e => e.IsMain)
                .HasDatabaseName("all_paragliding_locations_is_main_idx");

            // Index on Name
            entity.HasIndex(e => e.Name)
                .HasDatabaseName("all_paragliding_locations_name_idx");

            entity.Property(e => e.IsActive)
                .HasDefaultValue(true);

            entity.Property(e => e.IsMain)
                .HasDefaultValue(false);

            entity.HasMany(e => e.ForecastCaches)
                .WithOne(e => e.ParaglidingLocation)
                .HasForeignKey(e => e.LocationId)
                .HasConstraintName("forecast_cache_location_id_fkey")
                .OnDelete(DeleteBehavior.NoAction);
        });

        // Configure ForecastCache
        modelBuilder.Entity<ForecastCache>(entity =>
        {
            entity.HasKey(e => e.Id);

            // Database generates primary key IDs (bigserial)
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd();

            // Unique constraint on LocationId and Time
            entity.HasAlternateKey(e => new { e.LocationId, e.Time })
                .HasName("forecast_cache_location_id_time_key");

            // Index on LocationId and Time
            entity.HasIndex(e => new { e.LocationId, e.Time })
                .HasDatabaseName("idx_forecast_cache_location_time");

            // Index on Time
            entity.HasIndex(e => e.Time)
                .HasDatabaseName("idx_forecast_cache_time");

            // Index on LocationId
            entity.HasIndex(e => e.LocationId)
                .HasDatabaseName("forecast_cache_location_id_idx");

            // Check constraint: IsDay must be 0 or 1
            entity.ToTable(t => t.HasCheckConstraint("forecast_cache_is_day_check",
                "is_day = ANY (ARRAY[0, 1])"));

            // Default values
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()");

            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()");

            entity.Property(e => e.IsYrData)
                .HasDefaultValue(false);

            // Explicitly mark LocationId and Time as not value-generated for FlexLabs upsert
            entity.Property(e => e.LocationId)
                .ValueGeneratedNever();

            entity.Property(e => e.Time)
                .ValueGeneratedNever();
        });
    }
}
