// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WindLordApi.Data;

#nullable disable

namespace WindLordApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WindLordApi.Data.Models.StationData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<bool>("IsCompressed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_compressed");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("station_id");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("WindGust")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("wind_gust");

                    b.Property<decimal?>("WindMinSpeed")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("wind_min_speed");

                    b.Property<decimal>("WindSpeed")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("wind_speed");

                    b.HasKey("Id");

                    b.HasAlternateKey("StationId", "UpdatedAt");

                    b.HasIndex("StationId", "UpdatedAt")
                        .IsUnique()
                        .HasDatabaseName("unique_station_timestamp");

                    b.ToTable("station_data", t =>
                        {
                            t.HasCheckConstraint("station_data_direction_check", "direction >= 0 AND direction <= 360");
                        });
                });

            modelBuilder.Entity("WindLordApi.Data.Models.WeatherStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("Altitude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("altitude");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_main");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("station_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .IsUnique()
                        .HasDatabaseName("weather_stations_station_id_unique");

                    b.ToTable("weather_stations", t =>
                        {
                            t.HasCheckConstraint("check_provider_not_empty", "provider IS NOT NULL AND provider <> ''");
                        });
                });

            modelBuilder.Entity("WindLordApi.Data.Models.StationData", b =>
                {
                    b.HasOne("WindLordApi.Data.Models.WeatherStation", "WeatherStation")
                        .WithMany("StationData")
                        .HasForeignKey("StationId")
                        .HasPrincipalKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_station_data_station_id");

                    b.Navigation("WeatherStation");
                });

            modelBuilder.Entity("WindLordApi.Data.Models.WeatherStation", b =>
                {
                    b.Navigation("StationData");
                });
#pragma warning restore 612, 618
        }
    }
}
