using WindLordApi.Data.Models;

namespace WindLordApi.Integrations.Holfuy;

/// <summary>
/// Maps Holfuy API response data to domain models for database storage.
/// </summary>
public class HolfuyMappingService : IHolfuyMapping
{
    /// <summary>
    /// Maps Holfuy API response data to StationData format for database storage.
    /// </summary>
    /// <param name="holfuyData">Array of Holfuy station data</param>
    /// <returns>Array of StationData objects (without Id) ready for database insertion</returns>
    public List<StationData> MapHolfuyToStationData(
        IReadOnlyList<HolfuyStationData> holfuyData)
    {
        return holfuyData
            .Where(station =>
            {
                // Filter out stations with invalid coordinates
                if (!double.TryParse(station.Location.Latitude, out var lat) ||
                    !double.TryParse(station.Location.Longitude, out var lng))
                {
                    return false;
                }

                return lat != 0
                    && lng != 0
                    && lat >= -90
                    && lat <= 90
                    && lng >= -180
                    && lng <= 180;
            })
            .Select(station =>
            {
                // Parse dateTime string to DateTime
                var updatedAt = DateTime.TryParse(station.DateTime, out var parsedDateTime)
                    ? parsedDateTime.ToUniversalTime()
                    : DateTime.UtcNow;

                // Normalize wind direction to ensure it's within 0-360 range
                var direction = (int)Math.Round(station.Wind.Direction);
                direction = ((direction % 360) + 360) % 360;

                return new StationData
                {
                    // Id is not set - will be generated by database
                    StationId = station.StationId.ToString(),
                    WindSpeed = (decimal)station.Wind.Speed,
                    WindGust = (decimal)station.Wind.Gust,
                    WindMinSpeed = (decimal)station.Wind.Min,
                    Direction = direction,
                    Temperature = station.Temperature.HasValue ? (decimal)station.Temperature.Value : null,
                    UpdatedAt = updatedAt,
                    IsCompressed = false
                };
            })
            .ToList();
    }

    /// <summary>
    /// Maps Holfuy API response data to WeatherStation format for database storage.
    /// </summary>
    /// <param name="holfuyData">Array of Holfuy station data</param>
    /// <returns>Array of WeatherStation objects (without Id and UpdatedAt) ready for database insertion</returns>
    public List<WeatherStation> MapHolfuyToWeatherStation(
        IReadOnlyList<HolfuyStationData> holfuyData)
    {
        return holfuyData
            .Where(station =>
            {
                // Filter out stations with invalid coordinates
                if (!double.TryParse(station.Location.Latitude, out var lat) ||
                    !double.TryParse(station.Location.Longitude, out var lng))
                {
                    return false;
                }

                return lat != 0
                    && lng != 0
                    && lat >= -90
                    && lat <= 90
                    && lng >= -180
                    && lng <= 180;
            })
            .Select(station =>
            {
                // Parse latitude/longitude strings to decimal (with rounding to 5 decimals)
                var latitude = double.Parse(station.Location.Latitude);
                var longitude = double.Parse(station.Location.Longitude);
                var roundedLat = Math.Round(latitude, 5);
                var roundedLng = Math.Round(longitude, 5);

                return new WeatherStation
                {
                    // Id is not set - will be generated by database
                    StationId = station.StationId.ToString(),
                    Name = station.StationName,
                    Latitude = (decimal)roundedLat,
                    Longitude = (decimal)roundedLng,
                    Altitude = (int)Math.Round(station.Location.Altitude),
                    Country = "Norway",
                    IsActive = true,
                    Provider = "Holfuy",
                    IsMain = true
                    // UpdatedAt is not set - will be set by database
                };
            })
            .ToList();
    }
}

