on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    # Use the labels currently assigned to your self-hosted runner
    runs-on: [self-hosted, Linux, arm64]

    steps:
      - uses: actions/checkout@v5

      - name: Check .NET Version
        run: dotnet --info

      - name: Build Worker
        run: dotnet publish -c Release -o ./publish
